apiVersion: v1
kind: Service
metadata:
  name: {{ include "permoney.fullname" . }}
  labels:
    {{- include "permoney.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/component: web
    {{- include "permoney.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
